# Generated by Django 3.2.5 on 2021-07-26 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('proprietario', models.CharField(max_length=100, verbose_name='Proprietário')),
                ('credito', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Crédito')),
                ('saldo', models.FloatField(default=0.0)),
                ('tipo', models.CharField(choices=[('Conta Bônus', 'Conta Bônus'), ('Conta Poupança', 'Conta Poupança')], max_length=20, verbose_name='Tipo de Conta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
            },
        ),
        migrations.CreateModel(
            name='ContaBonus',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.conta')),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Pontuação')),
            ],
            options={
                'verbose_name': 'Conta Bônus',
            },
            bases=('core.conta',),
        ),
        migrations.CreateModel(
            name='ContaPoupanca',
            fields=[
                ('conta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.conta')),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Taxa de Juros')),
            ],
            options={
                'verbose_name': 'Conta Poupança',
            },
            bases=('core.conta',),
        ),
    ]
