# Generated by Django 3.2.5 on 2021-07-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('proprietario', models.CharField(max_length=100, verbose_name='Proprietário')),
                ('credito', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Crédito')),
                ('saldo', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Conta',
            },
        ),
    ]
