# Generated by Django 3.2.5 on 2021-07-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='credito',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Crédito'),
        ),
    ]
