name: Pipeline Release

on:
  push:
    branches:
      - release

  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --exclude .git, commit-msg.py, *migrations*, *tests*, bank_system*, venv_bank_system*, venv_bank, core/templatetags/*, manage.py, core/apps.py, core/admin.py, core/__init__.py
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report
      - name: Django Testing
        run: |
          python3 manage.py test
      - name: Generate .zip from system packages
        run: |
          python -m zipfile -c bank bank_system/
      - name: set github credentials
        run: |
          git config --global user.email "wesleygurgel27@gmail.com"
          git config --global user.name "Wesley Gurgel"
      - name: check for changes
        run: |
          git status
      - name: stage changed files
        run: |
         git add .
      - name: commit changed files
        run: |
         git commit -m "Auto updating system packages in bank.zip"
      - name: push code to release
        run: |
         git push origin release
